-- MySQL Script generated by MySQL Workbench
-- Tue May  6 11:28:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Employee
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Employee` ;

-- -----------------------------------------------------
-- Schema Employee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Employee` DEFAULT CHARACTER SET utf8 ;
USE `Employee` ;

-- -----------------------------------------------------
-- Table `Employee`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee`.`employees` ;

CREATE TABLE IF NOT EXISTS `Employee`.`employees` (
                                                      `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                      `name` VARCHAR(150) NOT NULL,
    `last_name` VARCHAR(150) NOT NULL,
    `document_type` ENUM('RC', 'TI', 'CC', 'TE', 'CE', 'NIT', 'PP', 'PEP', 'DIE') NOT NULL,
    `id_number` VARCHAR(15) NOT NULL,
    `date_of_birth` DATE NOT NULL,
    `date_of_joining_company` DATE NOT NULL,
    `position` VARCHAR(50) NOT NULL,
    `salary` DECIMAL(14,2) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_number_UNIQUE` (`id_number` ASC) VISIBLE)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
